# Generated by Django 6.0.5 on 2026-05-18 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_nis'),
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('detail', 'Commande Détail'), ('gros', 'Commande Gros')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'created_at'], name='idx_commande_statut_date'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['prevendeur', 'statut'], name='idx_commande_prev_statut'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['livreur', 'statut'], name='idx_commande_livr_statut'),
        ),
    ]
