# Generated by Django 6.0.3 on 2026-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=15),
        ),
    ]
