# Generated by Django 6.0.3 on 2026-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_montant_paye_alter_commande_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='commandes_photos/'),
        ),
    ]
