# Generated by Django 6.0.3 on 2026-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('credit', 'Crédit'), ('non_paye', 'Non Payé')], default='especes', max_length=20),
        ),
    ]
