# Generated by Django 6.0.5 on 2026-05-15 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement')], max_length=20)),
                ('motif', models.CharField(choices=[('achat', 'Achat fournisseur'), ('vente', 'Vente client'), ('retour', 'Retour'), ('perte', 'Perte / Casse'), ('ajustement', 'Ajustement inventaire'), ('transfert', 'Transfert')], default='ajustement', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_avant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_apres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='products.produit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
