# Generated by Django 6.0.3 on 2026-05-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.CharField(choices=[('achat', 'Achat fournisseur'), ('vente', 'Vente client'), ('retour', 'Retour'), ('non_conforme', 'Non Conforme'), ('perte', 'Perte / Casse'), ('ajustement', 'Ajustement inventaire'), ('transfert', 'Transfert')], default='ajustement', max_length=20),
        ),
    ]
