# Generated by Django 6.0.5 on 2026-07-01 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_charge', models.CharField(choices=[('carburant', 'Carburant'), ('vidange', 'Vidange'), ('reparation', 'Réparation'), ('pneumatique', 'Pneumatique (Pneu)'), ('lavage', 'Lavage'), ('vignette', 'Vignette'), ('assurance', 'Assurance'), ('amende', 'Amende'), ('salaire_chauffeur', 'Salaire chauffeur'), ('peage', 'Péage'), ('autre', 'Autre')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('camion', models.CharField(blank=True, help_text='Immatriculation ou nom du camion', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
