# Generated by Django 6.0.5 on 2026-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_remove_charge_camion_alter_charge_type_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='type_charge',
            field=models.CharField(choices=[('carburant', 'Carburant'), ('vidange', 'Vidange'), ('reparation', 'Réparation'), ('pneumatique', 'Pneumatique (Pneu)'), ('lavage', 'Lavage'), ('vignette', 'Vignette'), ('assurance', 'Assurance'), ('amende', 'Amende'), ('peage', 'Péage'), ('location_camion', 'Location camion'), ('autre', 'Autre')], max_length=50),
        ),
    ]
