# Generated by Django 6.0.3 on 2026-06-16 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_remove_client_wilaya'),
        ('products', '0007_produit_bouteilles_par_carton'),
        ('ventes', '0005_alter_vente_mode_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], db_index=True, default='en_attente', max_length=15)),
                ('motif', models.TextField(blank=True, help_text='Raison du retour')),
                ('mode_remboursement', models.CharField(choices=[('avoir', 'Avoir (crédit client)'), ('remboursement', 'Remboursement cash'), ('echange', 'Échange de produit')], default='avoir', max_length=15)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='clients.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_crees', to=settings.AUTH_USER_MODEL)),
                ('vente_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Retour Client',
                'verbose_name_plural': 'Retours Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_retour', models.CharField(choices=[('carton', 'Carton(s)'), ('bouteille', 'Bouteille(s) / Unité(s)')], default='carton', max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_en_cartons', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='retours.retourclient')),
            ],
        ),
    ]
