# Generated by Django 6.0.5 on 2026-05-15 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('type_paiement', models.CharField(choices=[('vente', 'Règlement vente'), ('achat', 'Paiement fournisseur'), ('autre', 'Autre')], max_length=20)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('mobile', 'Mobile payment')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='valide', max_length=20)),
                ('vente_ref', models.CharField(blank=True, max_length=50)),
                ('achat_ref', models.CharField(blank=True, max_length=50)),
                ('client_nom', models.CharField(blank=True, max_length=200)),
                ('fournisseur_nom', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reference_bancaire', models.CharField(blank=True, max_length=100)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('execute', 'Exécuté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements', to='hr.employe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
