# Generated by Django 6.0.5 on 2026-05-15 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('credit', 'Crédit')], default='especes', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bon_achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.bonachat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.produit')),
            ],
        ),
    ]
