# Generated by Django 6.0.5 on 2026-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonachat',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures_achats/'),
        ),
    ]
