# Generated by Django 6.0.5 on 2026-06-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_bonachat_facture_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneachat',
            name='quantite_offerte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
