# Generated by Django 6.0.5 on 2026-06-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_add_quantite_offerte_to_ligne_achat'),
        ('products', '0007_produit_bouteilles_par_carton'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneachat',
            name='produit_offert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_offert', to='products.produit'),
        ),
    ]
