# Generated by Django 6.0.5 on 2026-05-18 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_nis'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], db_index=True, default='confirmee', max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('detail', 'Vente Détail'), ('gros', 'Vente Gros')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['type_vente', 'created_at'], name='idx_vente_type_date'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['date', 'type_vente'], name='idx_vente_date_type'),
        ),
    ]
