# Generated by Django 6.0.3 on 2026-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_vente_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('brouillon', 'Brouillon'), ('confirmee', 'Confirmée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
