# Generated by Django 6.0.3 on 2026-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_alter_vente_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('credit', 'Crédit'), ('non_paye', 'Non Payé')], default='especes', max_length=20),
        ),
    ]
