# Generated by Django 6.0.3 on 2026-05-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('prevendeur_gros', 'Prévendeur Gros'), ('prevendeur_detail', 'Prévendeur Détail'), ('livreur_gros', 'Livreur Gros'), ('livreur_detail', 'Livreur Détail'), ('magasinier', 'Magasinier'), ('comptable', 'Comptable'), ('autre', 'Autre')], max_length=20),
        ),
    ]
