# Generated by Django 6.0.3 on 2026-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_n_article_client_nif_client_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nis',
            field=models.CharField(blank=True, max_length=50, verbose_name="NIS (N° d'Identification Statistique)"),
        ),
    ]
