# Generated by Django 6.0.5 on 2026-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_nis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wilaya',
        ),
    ]
