# Generated by Django 6.0.5 on 2026-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialite',
            field=models.CharField(choices=[('detail', 'Détail (carton)'), ('gros', 'Gros (palette)'), ('les_deux', 'Détail & Gros')], default='les_deux', help_text='Prévendeur: type de commandes autorisées. Livreur: type de livraisons assignées.', max_length=20),
        ),
    ]
