# Generated by Django 6.0.3 on 2026-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='n_article',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Article'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='nif',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='rc',
            field=models.CharField(blank=True, max_length=50, verbose_name='RC (Registre de commerce)'),
        ),
    ]
