# Generated by Django 6.0.3 on 2026-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_fournisseur_n_article_fournisseur_nif_fournisseur_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='nis',
            field=models.CharField(blank=True, max_length=50, verbose_name="NIS (N° d'Identification Statistique)"),
        ),
    ]
