# Generated by Django 6.0.5 on 2026-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_fournisseur_nis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='wilaya',
        ),
    ]
