# Generated by Django 6.0.5 on 2026-05-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('kg', 'Kilogramme'), ('litre', 'Litre'), ('carton', 'Carton'), ('pack', 'Pack'), ('sac', 'Sac')], default='carton', max_length=20)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_detail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_gros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimum', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='products.categorie')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
