# Generated by Django 6.0.3 on 2026-05-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('carton', 'Carton'), ('palette', 'Palette')], default='carton', max_length=20),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
