# Generated by Django 6.0.3 on 2026-05-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='unite',
        ),
        migrations.AddField(
            model_name='produit',
            name='cartons_par_palette',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de cartons dans une palette'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat par palette", max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_detail',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente par carton (détail)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_gros',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente par carton (gros)', max_digits=10),
        ),
    ]
