# Generated by Django 6.0.3 on 2026-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_cartons_par_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
