# Generated by Django 6.0.5 on 2026-05-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_produit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='actif',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_actuel',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['actif', 'stock_actuel'], name='idx_produit_actif_stock'),
        ),
    ]
