# Generated by Django 6.0.3 on 2026-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_volume_detail',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix de vente par carton appliqué au-delà du seuil (Détail)', max_digits=10),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_volume',
            field=models.PositiveIntegerField(default=0, help_text='Quantité minimum pour appliquer le prix de volume (Détail)'),
        ),
    ]
