# Generated by Django 6.0.3 on 2026-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_produit_prix_volume_detail_produit_seuil_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='bouteilles_par_carton',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de bouteilles (unités) dans un carton'),
        ),
    ]
